#! /bin/sh

# Release version of the Bittorensimag wrapper script. The assembly created an
# uber-jar so all we need is a java -jar command.

dir="$(dirname "$0")"
exec java -jar "$dir"/${project.artifactId}-${project.version}-jar-with-dependencies.jar "$@"
